### ISSUE TITLE
Add support for .gitattributes

### ISSUE THREAD

**Issue by martinvonz** [jj-vcs/jj#53]
We'll probably want to support at least the `eol` attribute. I noticed while using jj in a working copy shared with git that some files appeared modified because they had LF in the commit and CRLF in the working copy.

**Comment by WonderBeat** [comment]
And also there are tools like [git-crypt](https://github.com/AGWA/git-crypt) that use gitattributes. 
`jj` marks all git-crypt decrypted files as modified :(

**Comment by martinvonz** [comment]
> And also there are tools like [git-crypt](https://github.com/AGWA/git-crypt) that use gitattributes. `jj` marks all git-crypt decrypted files as modified :(

That seems to rely on the smudge/clean filters. Perhaps we'll want to support those too. I haven't thought much about how to implement that or what consequences it would have. I also haven't yet checked when Git runs them. I specifically wonder if they're *only* used when checking out from the index to the working copy or if they're also used e.g. when doing operations in memory.

**Comment by xelxebar** [comment]
Spitballing a bit here, but `git diff`ing between commits works just fine on encrypted files, so clean at least has got to be working on in-memory ops.

**Comment by martinvonz** [comment]
Speaking of that, there's an annoying special case that I don't think we're going to support: A file can have the same content in two commits but different .gitattributes, which ideally should make it show up in diffs. For example, let's say a file is committed with LF line endings, and in commit A it has a .gitattributes that says to convert those to CRLF and in commit B it doesn't have any .gitattributes. When diffing that file, you could argue that you should see the change in line endings. That would make diffing slow, however, since we can't say that a tree/file is unchanged if there are changes in .gitattributes in a parent directory. I asked the Git team at Google about this case a long time ago, and my recollection is that Git doesn't handle that case. It's of course easy to check but I haven't.

**Comment by kamalmarhubi** [comment]
> For example, let's say a file is committed with LF line endings, and in commit A it has a .gitattributes that says to convert those to CRLF and in commit B it doesn't have any .gitattributes. When diffing that file, you could argue that you should see the change in line endings.

I tested this out, and I'm pretty sure git doesn't handle it.

<details><summary>Click to see transcript of testing it out</summary>
Create a test repo

```
❯ git init test-eol-attr
Initialized empty Git repository in /private/tmp/test-eol-attr/.git/
❯ cd test-eol-attr/
❯ git commit --allow-empty -m'Root commit (empty)'
[main (root-commit) 21742c4] Root commit (empty)
```

Now add a file with LF line endings:
```
❯ seq 1 5 > test
❯ git add -p
No changes.
❯ git add test
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a                    |1.2.3.4.5.|
0000000a
❯ git commit -m'Add 1-10 with LF line endings (\x0a)'
[main 8f2afec] Add 1-10 with LF line endings (\x0a)
 1 file changed, 5 insertions(+)
 create mode 100644 test
```

Now set `eol=crlf` in `.gitattributes`
```
❯ echo 'test text eol=crlf' >> .gitattributes
❯ git checkout test
Updated 0 paths from the index
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a                    |1.2.3.4.5.|
0000000a
❯ git add .gitattributes
❯ git commit -m'Add .gitattributes setting eol to CRLF (\x0d\x0a)'
[main fe06662] Add .gitattributes setting eol to CRLF (\x0d\x0a)
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes
```

At this point, git see no differences, and the file in the working copy still has LF line endings:
```
❯ git checkout -p
No changes.
❯ git checkout -p test
No changes.
❯ git checkout test
Updated 0 paths from the index
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a                    |1.2.3.4.5.|
0000000a
```

Adding two more lines still leaves the file with LF line endings:
```
❯ seq 6 7 >> test
❯ git add -p
warning: in the working copy of 'test', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'test', LF will be replaced by CRLF the next time Git touches it
diff --git a/test b/test
index 8a1218a..06e567b 100644
--- a/test
+++ b/test
@@ -3,3 +3,5 @@
 3
 4
 5
+6
+7
(1/1) Stage this hunk [y,n,q,a,d,e,?]? y
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
❯ git commit -m'Add two more lines'
[main bf9e4b4] Add two more lines
 1 file changed, 2 insertions(+)
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
```

Even trying to `checkout` the file leaves it unchanged:
```
❯ git checkout test
Updated 0 paths from the index
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
❯ git checkout -f test
Updated 0 paths from the index
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
```
It's only when I take an action where git itself modifies the working copy file that it changes the line endings:
```
❯ git checkout -p HEAD~
diff --git b/test a/test
index 06e567b..8a1218a 100644
--- b/test
+++ a/test
@@ -3,5 +3,3 @@
 3
 4
 5
-6
-7
(1/1) Apply this hunk to index and worktree [y,n,q,a,d,e,?]? y

❯ hexdump -C test
00000000  31 0d 0a 32 0d 0a 33 0d  0a 34 0d 0a 35 0d 0a     |1..2..3..4..5..|
0000000f
```

Finally, `git diff` doesn't show a change in line endings in the diff, even against the working copy after running dos2unix (it does print a warning though):
```
❯ dos2unix test
dos2unix: converting file test to Unix format...
❯ git diff
warning: in the working copy of 'test', LF will be replaced by CRLF the next time Git touches it
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
❯ git checkout -p test
warning: in the working copy of 'test', LF will be replaced by CRLF the next time Git touches it
No changes.
❯ hexdump -C test
00000000  31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a        |1.2.3.4.5.6.7.|
0000000e
❯ git checkout test
Updated 1 path from the index
❯ hexdump -C test
00000000  31 0d 0a 32 0d 0a 33 0d  0a 34 0d 0a 35 0d 0a 36  |1..2..3..4..5..6|
00000010  0d 0a 37 0d 0a                                    |..7..|
00000015
```
</details>

**Comment by martinvonz** [comment]
Thanks for checking!

**Comment by omasanori** [comment]
Indeed the lack of `eol=crlf` support prevents me from using `jj` with Windows-specific files like `.cmd` files for AppVayor CI...

**Comment by martinvonz** [comment]
> Indeed the lack of `eol=crlf` support prevents me from using `jj` with Windows-specific files like `.cmd` files for AppVayor CI...

Just to make sure you know, you should still be able to use jj in a non-colocated workspace, i.e. if you do `jj init --git-repo=<path to git repo>` outside of the git repo's working copy.

**Comment by kevboh** [comment]
> > And also there are tools like [git-crypt](https://github.com/AGWA/git-crypt) that use gitattributes. `jj` marks all git-crypt decrypted files as modified :(
> 
> That seems to rely on the smudge/clean filters. Perhaps we'll want to support those too. I haven't thought much about how to implement that or what consequences it would have. I also haven't yet checked when Git runs them. I specifically wonder if they're _only_ used when checking out from the index to the working copy or if they're also used e.g. when doing operations in memory.

fwiw, I am very much interested in both eol attributes and clean/smudge via https://github.com/elasticdog/transcrypt. Currently working in a repo that is incompatible with jj because it uses both of these.

**Comment by stacyharper** [comment]
I'd like to point another use-case I'd like to see covered. The need to define a header function:

https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header

**Comment by Byron** [comment]
When listening to @martinvonz 's [GitMerge talk](https://youtu.be/LV0JzI8IcCY?si=5r5tUd57waOvMBMe&t=218) he mentioned that attribute-driven filters aren't supported yet which brought me here.

I just wanted to point out that even without going full-on [`gitoxide`](https://github.com/GitoxideLabs/gitoxide), the [`gix-filter::Pipeline`](https://docs.rs/gix-filter/latest/gix_filter/struct.Pipeline.html) is what can be used to convert to and from git. With it one receives natural `git-lfs` support as well.

I hope that's helpful.

**Comment by Maverik** [comment]
Not honouring EOL is causing thousands of lines of diff for me, every single time I try to do something, even in files I haven't touched (because git is doing CRLF on Checkout and LF on Checkin). Combined with the built-in diff being essentially a plain text patch diff, I can't see anything where there's a hunk of 1000 lines with one ending, then another with 1000 and potentially followed by a third 1000 lines where the real change was probably 10 lines or so.

While this talk is about .gitattribute, of course this also ties in with .gitconfig stating the behaviour of EoL that is also not honoured at the moment.

**Comment by abenz1267** [comment]
I decided to start using jj in a colocated git repo and struck by exactly this. I hope this can be resolved at some point, until then i sadly can't use jj at work.

**Comment by alilleybrinker** [comment]
This is also a blocker for using `jj` with [`omnibor-rs`](https://github.com/omnibor/omnibor-rs). We have test files where we need to validate we can produce the same Artifact ID regardless of CRLF or LF newlines, so retaining those CRLF newlines is essential for us.

**Comment by r-oldenburg** [comment]
Same here. I am very sad not to be able to use it. But having literally thousands (>100000) changed files in my workspace... That won't work for me. As great as it may be. 

So sad. Have really been curious.

**Comment by ninety7** [comment]
I just started using jj with a colocated git repo on Windows. I was also having this issue, but a member of the community was kind enough to provide a workaround on #6493. Hope it works while this issue gets resolved.

**Comment by indirect** [comment]
Even if not exactly `.gitattributes`, I would greatly appreciate some mechanism to filter diffs similar to git's `textconv`. My current setup for encrypted dotfiles, but with the plaintext shown in `git diff`, looks like this:

```
# .gitattributes
*.age     diff=age
# .gitconfig
[diff "age"]
    textconv = chezmoi decrypt
```

**Comment by hauleth** [comment]
I am using `.gitattributes` to set additional merge flags for lock files. So these files are treated as binary files during merge. That way the conflicts in lock files are still marked as conflict, but there are no conflict markers in these files. This is useful, as it allows me to just reinstall dependencies and update that file without manually resolving conflicts (and manually editing locks is pain).

My global attributes file looks like this:

```
*.ex diff=elixir
*.exs diff=elixir
mix.lock merge=binary
*.erl diff=erlang
*.hrl diff=erlang
rebar.lock merge=binary
*.tex diff=tex
*.rs diff=rust
Cargo.lock merge=binary
*.css diff=css
*.md diff=markdown
flake.lock merge=binary
yarn.lock merge=binary
*.lockb diff=lockb
```

**Comment by rokups** [comment]
This is very important for multi-platform software. Consider following attribute:
```
*.sh text eol=lf
```

Even on windows it is important to keep `*.sh` formatted with LF file endings. Automatic line endings would corrupt these files.

**Comment by Tijs-B** [comment]
Similarly to https://github.com/jj-vcs/jj/issues/53#issuecomment-3186945910, at work we use ansible-vault to encrypt some secrets in a repo. We then use `.gitattributes` with such a textconv configuration to show diffs of decrypted values. It would be great if also conflicts could be managed and merged on the converted values instead of the encrypted values. Right now I have a custom merge tool that tries to merge two files by merging their decrypted contents. That works nicely for conflicts that can be solved automatically, however when there is conflict that can not be solved, there is nothing I can do except opening an editor.

**Comment by marksimpson82** [comment]
> This is very important for multi-platform software. Consider following attribute:
> 
> ```
> *.sh text eol=lf
> ```
> 
> Even on windows it is important to keep `*.sh` formatted with LF file endings. Automatic line endings would corrupt these files.

Agreed. **tl;dr** `.gitattributes` & `eol` makes a few annoying things just-work(tm), so supporting this would be greatly appreciated!

I'm just getting started with `jj` (seems nice!), but it'd be cool if this was fixed up. Common use case for me at a previous company was cross-platform bash scripts that ran on Linux, MacOS and Windows. Prior to the existence of (or perhaps our awareness of...) `.gitattributes` `eol`, we bodged line endings in a few ways, it was painful. We also ran bash scripts via docker, so it was surprising when a bash script failed in a Linux container run on a Windows machine. CRLF strikes again, d'oh!

Once we started using this feature it was a solved problem. I don't think it's that niche, as I've added `.gitattribute` files with `eol` on several projects since (including one this year where a Go project had, you guessed it, bash scripts that needed to run on Linux/Mac/Windows machines).

Cheers.

**Comment by cizra** [comment]
There have been several people here, asking for "huge diffs in Windows because all files in working copy are CRLF". I was confused about the same thing too :)

In fact, this problem gets solved by a completely different solution: every time when snapshotting data from files into repository history, normalize to LF via this setting:
```
jj config set --user working-copy.eol-conversion input
```

.gitattributes is good for recreating specific line endings if an external program actually needs a specific line ending:
- `.sh` needs to be LF (at least the shebang part), but `jj config set --user working-copy.eol-conversion input` already covers that case
- `.cmd` / `.bat` need to be CRLF, and it's the only use case for EOL conversion (that I know of) that's not already covered by `jj config set --user working-copy.eol-conversion input`.

cc people asking for this: @krobelus @Maverik @abenz1267 @r-oldenburg @rokups @marksimpson82

**Comment by vlsi** [comment]
>.cmd / .bat need to be CRLF, and it's the only use case for EOL conversion (that I know of) that's not already covered by jj config set --user working-copy.eol-conversion input.

`working-copy.eol-conversion input` does not cover it. With git, `.gitattributes` enforces eol even in the case user supplies a file with wrong eol.
For instance, with git, a `.bat` file with LF would be automatically converted to CRLF on commit, and bad `.bat` won't even reach repository.

On the other hand, if you go with `.eol-conversion input`, then you effectively rely on all the users to manually check for LF/CRLF. It is just a time bomb.

**Comment by alex-aua** [comment]
> > .cmd / .bat need to be CRLF, and it's the only use case for EOL conversion (that I know of) that's not already covered by jj config set --user working-copy.eol-conversion input.
> 
> `working-copy.eol-conversion input` does not cover it. With git, `.gitattributes` enforces eol even in the case user supplies a file with wrong eol. For instance, with git, a `.bat` file with LF would be automatically converted to CRLF on commit, and bad `.bat` won't even reach repository.
> 
> On the other hand, if you go with `.eol-conversion input`, then you effectively rely on all the users to manually check for LF/CRLF. It is just a time bomb.

Side note: I don't believe that this is how .gitattributes based normalization works. In my experience telling git to manage the file leads to git always checking in the _normalized_ version to the index.

If you tell git that *.bat files should be CRLF in the working copy, it will convert the file to LF in the index and restore CRLF on checkout.
```
*.bat text eol=crlf
```
Now, running `git show HEAD:path/to/file.bat > file-from-index.bat` will show that all line endings in `file-from-index.bat` are LF, while `path/to/file.bat` will have the correct CRLF line endings.

**Comment by dnagir** [comment]
> In fact, this problem gets solved by a completely different solution: every time when snapshotting data from files into repository history, normalize to LF via this setting:
> 
> ```
> jj config set --user working-copy.eol-conversion input
> ```

Unfortunately that doesn't solve a lot of problems. One example I have is a Go project that vendors other modules and when those modules contain their own `.gitattributes`, such as [this one](https://github.com/apapsch/go-jsonmerge/blob/90b01458c2af82553f17c56a431386c57a8a569f/.gitattributes#L7).

The `working-copy.eol-conversion` applies to the whole repository while `.gitattributes` can be more localised. This causes significant number of issues in similar scenarios on non-trivially sized projects.

**Comment by rameshvarun** [comment]
We have a monorepo with some Gradle projects - these come with eol configured for `.bat` files.

```
❯ cat .gitattributes
*.bat           text eol=crlf
```

Without support for .gitattributes, in a fresh checkout, jj will claim that the working copy has changes. I made a repro script showing git and jj disagreeing on whether the repo is clean.

[jj-repro.sh](https://github.com/user-attachments/files/29777345/jj-repro.sh)

**Comment by asemarafa** [comment]
For anyone on Linux/macOS hitting this in colocated repos because of vendored dependencies (or scripts with `eol=crlf`):

You can override it locally without touching the vendored `.gitattributes`:

```sh
echo "path/to/vendored/**/*.ps1 -eol" >> .git/info/attributes
git add --renormalize path/to/vendored/**/*.ps1
```

`.git/info/attributes` has higher precedence than working-tree `.gitattributes` and isn't tracked. The `--renormalize` updates Git's cached file size in `.git/index` without modifying any files on disk or staging changes (since the hash matches `HEAD`). 

Both `jj status` and `git status` stay clean after that.
